name: promina_task
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter 
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.9
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  image_picker: ^0.8.5+3
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.7.0
  retrofit: ^3.0.1
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.0
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  lint: ^1.8.2
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true

flutter_gen:
  output: lib/generated/